### ISSUE TITLE
Multiple calls to the same reporting endpoint

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-reporting#27]
The `/statistics` endpoint of the Reporting API returns all the statistics that populate dash cards for Freetown so only needs to be called once.
Instead, it is being called once per card.
(Note that you will need to log in as a Freetown user. You can create a user with the Freetown Manager role in the User Manager page.)

**Comment by dadiorchen** [comment]
@Kpoke can you give me the URL to trigger the caching?

**Comment by dadiorchen** [comment]
On the dev env, I found 503 unavailable error:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/5744708/167237141-4838c5d9-bdc4-47d5-9986-3431fcd086ea.png">

**Comment by dadiorchen** [comment]
The case is interesting, there are 6 requests happening at the same time,but just one succeeded,

**Comment by ZavenArra** [comment]
We implemented a cache in the reporting API, and implemented a pre-cache scheduled job to keep the cache fresh.   We will continue to make multiple requests, since the cards are independent codes to allow for separate deployment, but the API will now be fast because the response is cached and fresh.
